"""Deterministic SDK demo for real UI capture; no LLM or device access.

Upload this file through Agent > Runtime > Upload Python. No requirements or
secrets are needed with the supported Nexus Python build profile.
"""
import asyncio
from pathlib import Path
import tempfile

from nexus_agent.fastmcp import CurrentNexusMCP, NexusMCPServer

server = NexusMCPServer("Launch notes assistant")


@server.tool(chat=True, task=True, interactive=True)
async def launch_notes(message: str, nexus=CurrentNexusMCP()) -> dict:
    """Prepare a sample launch checklist after the caller confirms its audience."""
    await nexus.plan.set([
        {"id": "brief", "title": "Read the launch brief", "status": "running"},
        {"id": "audience", "title": "Confirm the audience", "status": "pending"},
        {"id": "notes", "title": "Create the Markdown checklist", "status": "pending"},
    ])
    await nexus.chat.say(
        "Let's prepare your launch checklist.\n\nThis deterministic SDK example "
        "uses no external model or personal device."
    )
    await nexus.plan.update("brief", status="completed")
    await nexus.plan.update("audience", status="running")
    response = await nexus.chat.ask(
        "Who is this launch checklist for?",
        key="launch-audience",
        kind="select",
        choices=[
            {"value": "developers", "label": "Developers"},
            {"value": "operators", "label": "Self-hosting operators"},
        ],
        timeout=600,
    )
    audience = "Developers" if response.value == "developers" else "Self-hosting operators"
    await nexus.plan.update("audience", status="completed", detail=audience)
    await nexus.plan.update("notes", status="running")
    markdown = (
        "# Launch checklist\n\n"
        f"**Audience:** {audience}\n\n"
        f"## Your brief\n\n{message}\n\n"
        "## Before sharing\n\n"
        "- [ ] Document the installation requirements.\n"
        "- [ ] Run one example end to end.\n"
        "- [ ] Explain device permissions and data boundaries.\n"
        "- [ ] Include sanitized screenshots and troubleshooting steps.\n\n"
        "> Generated by the deterministic Nexus SDK demonstration. "
        "This is a checklist, not a claim that the checks have passed.\n"
    )
    # write_text() targets an Attached Computer. A device-free hosted Agent
    # instead uploads its own temporary output through the private file API.
    with tempfile.TemporaryDirectory(prefix="nexus-launch-") as directory:
        output = Path(directory) / "launch-checklist.md"
        output.write_text(markdown, encoding="utf-8")
        reference = await asyncio.to_thread(
            nexus.output.upload_file, output, content_type="text/markdown", timeout=120
        )
    nexus.output.ready({"file_id": reference["file_id"]})
    await nexus.plan.update("notes", status="completed")
    await nexus.chat.say(
        f"Your checklist for **{audience}** is ready. Open **Files** to preview "
        "or download `launch-checklist.md`. Nothing was published or sent externally."
    )
    return {"status": "completed", "audience": audience, "file": "launch-checklist.md"}
