"""Keep every existing version URL on current docs. --check detects drift.

Version labels identify URL compatibility, not frozen software documentation.
Unexpected old-only files fail for review instead of being silently deleted.
"""
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]

def main():
    check = '--check' in sys.argv
    failures = []
    total = 0
    for prefix, current, sidebar in [('', 'docs-openwrt', 'openwrtSidebar'), ('sdk_', 'docs-sdk', 'sdkSidebar')]:
        locale = ROOT / 'i18n/en' / ('docusaurus-plugin-content-docs-sdk' if prefix else 'docusaurus-plugin-content-docs')
        versions = json.loads((ROOT / f'{prefix}versions.json').read_text(encoding='utf-8'))
        for version in versions:
            pairs = [(ROOT/current, ROOT/f'{prefix}versioned_docs/version-{version}'),
                     (locale/'current', locale/f'version-{version}')]
            for source, target in pairs:
                files = {p.relative_to(source): p for p in source.rglob('*') if p.is_file()}
                old = {p.relative_to(target) for p in target.rglob('*') if p.is_file()}
                if old - files.keys():
                    failures.append(f'Old-only files require review: {target}: {old-files.keys()}')
                for relative, path in files.items():
                    total += 1
                    destination = target/relative
                    if not destination.exists() or destination.read_bytes() != path.read_bytes():
                        if check: failures.append(str(destination.relative_to(ROOT)))
                        else:
                            destination.parent.mkdir(parents=True, exist_ok=True)
                            destination.write_bytes(path.read_bytes())
            # Dynamic sidebars expose new pages under every retained version URL.
            path=ROOT/f'{prefix}versioned_sidebars/version-{version}-sidebars.json'
            expected={sidebar:[{'type':'autogenerated','dirName':'.'}]}
            if not path.exists() or json.loads(path.read_text(encoding='utf-8')) != expected:
                if check: failures.append(str(path))
                else: path.write_text(json.dumps(expected,indent=2)+'\n',encoding='utf-8')
    if failures: raise SystemExit('Version documentation drift:\n'+'\n'.join(failures))
    print(f'All version docs match current content: {total} files '+('verified' if check else 'synchronized'))

if __name__ == '__main__': main()
